### ISSUE TITLE
Numbers never seem to match up

### ISSUE THREAD

**Issue by Santafegreenchile** [manu354/cryptocurrency-arbitrage#13]
Am I using this wrong or are the numbers wrong? For example, EXP on bittrex to Poloniex shows 0.757 to 0.779. But in reality, the prices are currently 0.78 (bitrex) to 0.777(Poloniex). So not only are the numbers not accurate, but the wrong exchange is placed as the lower price. And this is pretty much the norm, not the exception for almost every time I look up the actual prices vs. what your site says they're currently at for whichever coin I look up. I just don't see where your numbers are coming from instead because they don't match up with the sell, buy, 24-high, 24-low prices in the charts either. 

So either, I am totally using your site wrong, or something is really off with the way they are gathering the current prices on their respective markets.

**Comment by manu354** [comment]
That should be fixed in the latest comment with adding pm2. Can you check whether the issue is still there?

**Comment by danielfoster** [comment]
I'm experiencing the same issue. The software is reporting a 6.35% spread between MLN on Bitrex and Kraken, but in reality the difference is 0.7% when you go to buy and sell.

**Comment by manu354** [comment]
So this is #6 but I thought I fixed that.

**Comment by danielfoster** [comment]
I tried in a new browser to ensure it wasn't a cache issue and the 6.35% spread still appears on the hosted site.

**Comment by Primly** [comment]
I wonder if this the the hosted site still using numbers from cryptowatch for polonoiex?

**Comment by chillerfx** [comment]
the 1st thing that it's showing last price that exchange had a transaction, not the bid/ask price. Second thing that there could be a problem with Javascript way of doing math. Currently there's not math lib included for precise calculations... Not at least at this repo. You could check out my fork of this repo.. I currently rewrote most of the application code to be more readable and easier to maintain... The thing is you probably have to run the fork version yourself and there's some minor issues of error handling.

**Comment by manu354** [comment]
@Primly could be that the latest build failed

**Comment by manu354** [comment]
Chiller I'll run your version and see if it's better then will just fork everything

**Comment by monyobi** [comment]
I would suggest adding the order book as opposed to the bid/ask prices. This increases accuracy because you can match order sizes from different exchanges and actually say the amount of coin at which there is an arbitrage opportunity, i.e. you can buy 0.5 BTC from Poloniex at $2,500 and sell 0.5 BTC in Bittrex for $2,600.

**Comment by manu354** [comment]
This issue has been fixed!! The socket.io wasn't sending with new information because it was called 'news' not 'results'.
