### ISSUE TITLE
npm start error - gil-dev branch

### ISSUE THREAD

**Issue by Cozy35** [manu354/cryptocurrency-arbitrage#38]
Has anyone successfully installed and run the gil-dev branch to take care of the bid/ask price instead if the latest_price. I installed the latest nodejs V9.4.0 and get the following error: (I would appreciate any pointers on this)
+++++++++++++++++
D:\Bitcoin\arb\main.js:164
        })
         ^
SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptocurrency-arbitrage@1.4.0 start: `node main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptocurrency-arbitrage@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jannie\AppData\Roaming\npm-cache\_logs\2018-01-19T04_43_31
_878Z-debug.log

D:\Bitcoin\arb>
+++++++++++++++++

Thanks

**Comment by Cozy35** [comment]
I fixed the error. Now it seems that the console reports finishing function all the time as if in a loop state.

**Comment by PlayboySatoshi** [comment]
I also get this error. I installed your forked repo but still the same error. Could you please tell me how to fix it?
